import Head from 'next/head'
import { LandingPage } from '../components/LandingPage'



export default function Home() {
  return (
    <>
      <Head>
        <title>Monday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          @import url('https://fonts.cdnfonts.com/css/gill-sans-mt-2');
        </style>
        <style> 
          @import url('https://fonts.googleapis.com/css2?family=Genos:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap'); 
        </style>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Georama:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        </style>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <LandingPage/>
    </>
  )
}
